export const VITE_APP_OPEN_WEATHER_API_KEY = import.meta.env.VITE_APP_OPEN_WEATHER_API_KEY;
export const VITE_APP_ACCU_WEATHER_API_KEY = import.meta.env.VITE_APP_ACCU_WEATHER_API_KEY;
export const VITE_APP_NAVER_CLIENT_ID = import.meta.env.VITE_APP_NAVER_CLIENT_ID;
export const VITE_APP_NAVER_CLIENT_SECRET = import.meta.env.VITE_APP_NAVER_CLIENT_SECRET;
export const VITE_APP_STOCK_API_KEY = import.meta.env.VITE_APP_STOCK_API_KEY;
